from flask import Flask, render_template
from config import Config
import subprocess
from constants import CORAL_CLI_COMMAND

app = Flask(__name__)
app.config.from_object(Config)

@app.route("/")
def home():
    query = "SELECT author, commit__message FROM github.commits WHERE owner = 'kaveh0007' AND repo = 'flask-blog'" # This has to be generated by an Agent
    command = CORAL_CLI_COMMAND.copy()
    command.append(query)
    result = subprocess.run(command, capture_output=True, text=True)
    print(result)
    return render_template("home.html")